version: "3.9"
services:
  db:
    build: ./db/
    ports:
      - 3306:3306
    volumes:
      - /home/s1n7ax/Workspace/kt-kubernetes/02_microservice/db/init:/docker-entrypoint-initdb.d
    environment:
      - MARIADB_USER=s1n7ax 
      - MARIADB_PASSWORD=pass 
      - MARIADB_ROOT_PASSWORD=rootpass 
    network_mode: host

  vote-ms:
    build: ./vote-ms/
    ports:
      - 8000:8000
    network_mode: host
    environment:
      - DB_HOST=localhost

  result-ms:
    build: ./result-ms/
    ports:
      - 8001:8001
    network_mode: host
    environment:
      - DB_HOST=localhost

  vote-app:
    build:
      context: ./vote-app/
      args:
        - REACT_APP_VOTE_MS_HOST=localhost
        - REACT_APP_VOTE_MS_PORT=8000
    ports:
      - 3000:3000
    network_mode: host
  result-app:
    build:
      context: ./result-app/
      args:
        - REACT_APP_VOTE_MS_HOST=localhost
        - REACT_APP_VOTE_MS_PORT=8001
    ports:
      - 3001:3001
    network_mode: host
