version: "3.9"
services:
  db:
    build: ./db/
    ports:
      - 3306:3306
    environment:
      - MARIADB_USER=s1n7ax 
      - MARIADB_PASSWORD=pass 
      - MARIADB_ROOT_PASSWORD=rootpass 

  vote-ms:
    build: ./vote-ms/
    ports:
      - 8000:8000
    environment:
      - DB_HOST=db

  result-ms:
    build: ./result-ms/
    ports:
      - 8001:8001
    environment:
      - DB_HOST=db

  vote-app:
    build:
      context: ./vote-app/
      args:
        - REACT_APP_VOTE_MS_HOST=localhost
        - REACT_APP_VOTE_MS_PORT=8000
    ports:
      - 3000:3000
  result-app:
    build:
      context: ./result-app/
      args:
        - REACT_APP_VOTE_MS_HOST=localhost
        - REACT_APP_VOTE_MS_PORT=8001
    ports:
      - 3001:3001
