apiVersion: v1
kind: Service
metadata:
  name: result-app-service
  labels:
    type: result-app-service
spec:
  selector:
    type: result-app
  type: NodePort
  ports:
    - port: 3001
      targetPort: 3001
      nodePort: 30003

