apiVersion: v1
kind: Service
metadata:
  name: result-ms-service
  labels:
    type: result-ms-service
spec:
  selector:
    type: result-ms
  type: NodePort
  ports:
    - port: 8001
      targetPort: 8001
      nodePort: 30001
