apiVersion: v1
kind: Service
metadata:
  name: vote-app
  labels:
    type: vote-app-service
spec:
  selector:
    type: vote-app
  type: NodePort
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30002
