apiVersion: v1
kind: Service
metadata:
  name: vote-ms-service
  labels:
    type: vote-ms-service
spec:
  selector:
    type: vote-ms
  type: NodePort
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 30000
