apiVersion: v1
kind: Pod
metadata:
  name: result-app
  labels:
    type: result-app
spec:
  containers:
  - name: result-app
    image: s1n7ax/result-app:latest
    ports:
    - containerPort: 3001
    imagePullPolicy: Always
