apiVersion: v1
kind: Pod
metadata:
  name: result-ms
  labels:
    type: result-ms
spec:
  containers:
  - name: result-ms
    image: s1n7ax/result-ms:2.1
    ports:
    - containerPort: 8001
    env:
      - name: DB_HOST
        value: db
