apiVersion: v1
kind: Pod
metadata:
  name: vote-app
  labels:
    type: vote-app
spec:
  containers:
  - name: vote-app
    image: s1n7ax/vote-app:latest
    ports:
    - containerPort: 3000
    imagePullPolicy: Always
